spring:
  application:
    name: sample-spring-elasticsearch
  data:
    elasticsearch:
      cluster-name: es622
      cluster-nodes: 192.168.163.21:9300

  elasticsearch:
    rest:
      uris: http://192.168.163.21:9200

# 初始化时是否导入数据
initial-import:
  enabled: true